@baseUrl=http://localhost:3000
@createdHostId = {{createHost.response.body.$.id}}

### Create Host

# @name createHost
POST {{baseUrl}}/hosts
Content-Type: application/json

{
  "name": "google search",
  "address": "www.google.com"
}

### Read Hosts

GET {{baseUrl}}/hosts

### Read a host

GET {{baseUrl}}/hosts/{{createdHostId}}

### Update a host

PUT {{baseUrl}}/hosts/{{createdHostId}}
Content-Type: application/json

{
  "name": "Google Search",
  "address": "www.google.com"
}

### Delete a host

DELETE {{baseUrl}}/hosts/{{createdHostId}}

### Create reachability

POST {{baseUrl}}/hosts/{{createdHostId}}/reachabilities

### Read reachabilities by Host

GET {{baseUrl}}/hosts/{{createdHostId}}/reachabilities

### Read all reachabilities

GET {{baseUrl}}/reachabilities

### Create User

# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Carlos",
  "email": "carlos@email.com",
  "password": "123"
}
